use serde::{Deserialize, Deserializer, Serialize};
use std::ops::Deref;
use uuid::Uuid;

/// Helper function to convert a string to a deterministic UUID by hashing.
/// Used when the string is not a valid UUID format.
fn string_to_uuid(s: &str) -> Uuid {
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};

    let mut hasher = DefaultHasher::new();
    s.hash(&mut hasher);
    let h1 = hasher.finish();
    s.hash(&mut hasher);
    let h2 = hasher.finish();

    let mut bytes = [0u8; 16];
    bytes[0..8].copy_from_slice(&h1.to_le_bytes());
    bytes[8..16].copy_from_slice(&h2.to_le_bytes());

    // Set version to 4 (random) and variant bits
    bytes[6] = (bytes[6] & 0x0f) | 0x40;
    bytes[8] = (bytes[8] & 0x3f) | 0x80;

    Uuid::from_bytes(bytes)
}

/// Macro to define a newtype ID based on Uuid.
macro_rules! define_id_type {
    // This arm of the macro handles calls that don't specify extra derives.
    ($name:ident) => {
        define_id_type!($name,);
    };
    // This arm handles calls that do specify extra derives (like Eq).
    ($name:ident, $($extra_derive:ident),*) => {
        #[doc = concat!(stringify!($name), ": A newtype used to prevent mixing it with other ID values.")]
        #[derive(Debug, Clone, PartialEq, Serialize, Eq, Hash, $($extra_derive),*)]
        pub struct $name(Uuid);

        impl<'de> Deserialize<'de> for $name {
            fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
            where
                D: Deserializer<'de>,
            {
                let s = String::deserialize(deserializer)?;
                // Try to parse as UUID first, if that fails hash the string
                match Uuid::parse_str(&s) {
                    Ok(uuid) => Ok(Self(uuid)),
                    Err(_) => Ok(Self(string_to_uuid(&s))),
                }
            }
        }

        impl $name {
            /// Creates a new random ID.
            pub fn random() -> Self {
                Self(Uuid::new_v4())
            }

            /// Creates a new ID from a string.
            ///
            /// For testing and when a deterministic ID is needed.
            /// If the string is not a valid UUID, a deterministic UUID is
            /// generated by hashing the string bytes.
            pub fn new(s: impl AsRef<str>) -> Self {
                let s = s.as_ref();
                match Uuid::parse_str(s) {
                    Ok(uuid) => Self(uuid),
                    Err(_) => Self(string_to_uuid(s)),
                }
            }
        }

        /// Allows creating an ID from a Uuid.
        impl From<Uuid> for $name {
            fn from(uuid: Uuid) -> Self {
                Self(uuid)
            }
        }

        /// Allows converting an ID back into a Uuid.
        impl From<$name> for Uuid {
            fn from(id: $name) -> Self {
                id.0
            }
        }

        /// Allows getting a reference to the inner Uuid.
        impl AsRef<Uuid> for $name {
            fn as_ref(&self) -> &Uuid {
                &self.0
            }
        }

        /// Allows printing the ID.
        impl std::fmt::Display for $name {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "{}", self.0)
            }
        }

        /// Allows parsing an ID from a string slice.
        impl std::str::FromStr for $name {
            type Err = uuid::Error;

            fn from_str(s: &str) -> Result<Self, Self::Err> {
                Ok(Self(Uuid::parse_str(s)?))
            }
        }

        /// Allows comparing the ID with a Uuid.
        impl PartialEq<Uuid> for $name {
            fn eq(&self, other: &Uuid) -> bool {
                self.0 == *other
            }
        }

        /// Allows comparing the ID with a string slice.
        impl PartialEq<str> for $name {
            fn eq(&self, other: &str) -> bool {
                if let Ok(uuid) = Uuid::parse_str(other) {
                    self.0 == uuid
                } else {
                    false
                }
            }
        }
    };
}

define_id_type!(AgentId);
define_id_type!(ThreadId);
define_id_type!(RunId);
define_id_type!(MessageId);

/// A tool call ID.
/// Used by some providers to denote a specific ID for a tool call generation, where the result of the tool call must also use this ID.
#[derive(Debug, PartialEq, Eq, Deserialize, Serialize, Clone)]
pub struct ToolCallId(String);

/// Tool Call ID
///
/// Does not follow UUID format, instead uses "call_xxxxxxxx"
impl ToolCallId {
    pub fn random() -> Self {
        let uuid = &Uuid::new_v4().to_string()[..8];
        let id = format!("call_{uuid}");
        Self(id)
    }

    /// Creates a new ToolCallId from a string.
    ///
    /// The string is used directly as the ID value.
    pub fn new(s: impl Into<String>) -> Self {
        Self(s.into())
    }
}

impl Deref for ToolCallId {
    type Target = str;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // Test whether tool call ID has same format as rest of AG-UI
    #[test]
    fn test_tool_call_random() {
        let id = super::ToolCallId::random();
        assert_eq!(id.0.len(), 5 + 8);
        assert!(id.0.starts_with("call_"));
        dbg!(id);
    }

    #[test]
    fn test_message_id_deserialize_valid_uuid() {
        let uuid_str = "\"550e8400-e29b-41d4-a716-446655440000\"";
        let id: MessageId = serde_json::from_str(uuid_str).unwrap();
        assert_eq!(id.to_string(), "550e8400-e29b-41d4-a716-446655440000");
    }

    #[test]
    fn test_message_id_deserialize_langgraph_format() {
        // LangGraph uses "lc_run--<uuid>" format which is NOT a valid UUID
        let langgraph_id = "\"lc_run--019bcffd-726e-7ca1-9708-98f26a168272\"";
        let id: MessageId = serde_json::from_str(langgraph_id).unwrap();
        // Should not panic, and should produce a deterministic UUID
        assert!(!id.to_string().is_empty());

        // Verify it's deterministic (same input = same output)
        let id2: MessageId = serde_json::from_str(langgraph_id).unwrap();
        assert_eq!(id, id2);
    }

    #[test]
    fn test_run_id_deserialize_non_uuid_string() {
        let arbitrary_id = "\"my-custom-run-id-123\"";
        let id: RunId = serde_json::from_str(arbitrary_id).unwrap();
        assert!(!id.to_string().is_empty());

        // Verify determinism
        let id2: RunId = serde_json::from_str(arbitrary_id).unwrap();
        assert_eq!(id, id2);
    }

    #[test]
    fn test_new_and_deserialize_produce_same_result() {
        // The new() method and deserialize should produce the same UUID for the same input
        let langgraph_id = "lc_run--019bcffd-726e-7ca1-9708-98f26a168272";
        let from_new = MessageId::new(langgraph_id);
        let from_deser: MessageId =
            serde_json::from_str(&format!("\"{}\"", langgraph_id)).unwrap();
        assert_eq!(from_new, from_deser);
    }

    #[test]
    fn test_serialize_roundtrip_valid_uuid() {
        let original = MessageId::random();
        let serialized = serde_json::to_string(&original).unwrap();
        let deserialized: MessageId = serde_json::from_str(&serialized).unwrap();
        assert_eq!(original, deserialized);
    }
}
